name: console_bars
description: A package for creating a customizable progress bar in console easily.
version: 1.2.1
homepage: https://github.com/RohitEdathil/ConsoleBars

environment:
  sdk: ">=2.14.4 <4.0.0"

dev_dependencies:
  lints: ^1.0.0
