name: cd-action-publish
on:
  release:
    types: [published] 

jobs:

  publish-to-pub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: 🔧 Setup Dart SDK
        uses: dart-lang/setup-dart@v1.0 # setups dart sdk on this machine
      - name: 🚀Publish
        uses: RatakondalaArun/pub.dev-cd@v1.0
        with:
          creditionals: ${{secrets.PUB_CREDITIONALS}}
      
